apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-dzhao-tenant/dzhao-devfile-sample/devfile-sample@sha256:cbde2f7693c9d9094a91eff20f2b61bf8b9d1f8bf99742e78f490037ee41eccd
        name: my-nodejs
        resources: {}
status: {}
